version: "3.3"
services:

    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3001:3001"
      volumes:
        - "/code"
      depends_on:
        - mongo
      links:
        - mongo
    mongo:
      image: mongo
      volumes:
          - mongodb-data:/data/db
      ports:
          - 27017:27017
volumes:
  mongodb-data: